version: '3.8'

services:
  yarn-scheduler:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      # Mount Hadoop configuration if available
      # - /etc/hadoop/conf:/etc/hadoop/conf:ro
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - STORAGE_TYPE=sqlite
      - SQLITE_DB_PATH=/app/data/yarn-scheduler.db
      # - HADOOP_CONF_DIR=/etc/hadoop/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/queues', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s